[default.extend-words]
Pagent = "Pagent"
testng = "testng"
Varifier = "Varifier"

[files]
extend-exclude = [
  "caffeine/src/jsr166Test/*",
  "caffeine/src/eclipseTest/*",
  "guava/src/compatibilityTest/java/com/github/benmanes/caffeine/guava/compatibility/*",
  "simulator/src/main/resources/com/github/benmanes/caffeine/cache/simulator/parser/lirs/*",
]
