[versions]
awaitility = "4.3.0"
caffeine = "3.2.1"
junit = "6.0.0-M1"
rxjava = "3.1.11-RC4"
versions = "0.52.0"

[libraries]
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
