[versions]
caffeine = "3.2.1"
failsafe = "3.3.2"
junit = "6.0.0-M1"
truth = "1.4.4"
versions = "0.52.0"

[libraries]
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
failsafe = { module = "dev.failsafe:failsafe", version.ref = "failsafe" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
