[versions]
caffeine = "3.2.3"
graal = "0.11.3"
junit-jupiter = "6.0.1"
truth = "1.4.5"
versions = "0.53.0"

[libraries]
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
graal = { id = "org.graalvm.buildtools.native", version.ref = "graal" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
