[versions]
caffeine = "3.2.1"
graal = "0.10.6"
junit = "5.13.2"
truth = "1.4.4"
versions = "0.52.0"

[libraries]
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
graal = { id = "org.graalvm.buildtools.native", version.ref = "graal" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
