[versions]
caffeine = "3.1.8"
graal = "0.9.25"
junit = "5.10.0"
truth = "1.1.5"
versions = "0.48.0"

[libraries]
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
graal = { id = "org.graalvm.buildtools.native", version.ref = "graal" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
