[versions]
caffeine = "3.2.3"
junit-jupiter = "6.1.0-M1"
reactor = "3.8.1"
truth = "1.4.5"
versions = "0.53.0"

[libraries]
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
reactor = { module = "io.projectreactor:reactor-core", version.ref = "reactor" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
