[versions]
caffeine = "3.1.8"
junit = "5.11.0-M2"
reactor = "3.6.7"
truth = "1.4.2"
versions = "0.51.0"

[libraries]
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
reactor = { module = "io.projectreactor:reactor-core", version.ref = "reactor" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
