name: lincheck
on: [ push, pull_request ]

env:
  ORG_GRADLE_PROJECT_checksumFailOn: build_finish
  ORG_GRADLE_PROJECT_checksumIgnore: false
  ORG_GRADLE_PROJECT_checksumPrint: true
  JAVA_VERSION: 17

jobs:
  lincheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-${{ github.job }}-${{ matrix.java }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run lincheck
        run: |
          set -eux
          ./gradlew lincheckTests
